version: 2.1

commands:
  checkout_and_install:
    description: "Checkout code and install yarn"
    steps:
      # Checking out the code
      - checkout
      # Restoring node_modules
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-{{ .Environment.CIRCLE_JOB }}-dependencies-
      # Installing dependencies
      - run: yarn install
      # Upload dependencies to cache
      - save_cache:
          paths:
            - node_modules
          key: v1-{{ .Environment.CIRCLE_JOB }}-dependencies-{{ checksum "package.json" }}

jobs:
  node12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout_and_install

      - run: yarn test

  node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout_and_install

      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - node6
      - node8
